print("Enter the number you want to see:")
print("Hex   Bin   ListHex   Bin")
print(" 1     2       3       4")
select = input("")
if(select == "1"):
	hexnum = int(input("Enter the number you want converted to hex: "))
	print(hex(hexnum))
elif(select == "2"):
	binnum = int(input("Enter the number you want converted to bin: "))
	print(bin(binnum))
elif(select == "3"):
	print("Decimal", 0, "= Hexadecimal",hex(0))
	print("Decimal", 1, "= Hexadecimal",hex(1))
	print("Decimal", 2, "= Hexadecimal",hex(2))
	print("Decimal", 3, "= Hexadecimal",hex(3))
	print("Decimal", 4, "= Hexadecimal",hex(4))
	print("Decimal", 5, "= Hexadecimal",hex(5))
	print("Decimal", 6, "= Hexadecimal",hex(6))
	print("Decimal", 7, "= Hexadecimal",hex(7))
	print("Decimal", 8, "= Hexadecimal",hex(8))
	print("Decimal", 9, "= Hexadecimal",hex(9))
	print("Decimal", 10, "= Hexadecimal",hex(10))
elif(select == "4"):
	print("Decimal", 0, "= Binary",hex(0))
	print("Decimal", 1, "= Binary",hex(1))
	print("Decimal", 2, "= Binary",hex(2))
	print("Decimal", 3, "= Binary",hex(3))
	print("Decimal", 4, "= Binary",hex(4))
	print("Decimal", 5, "= Binary",hex(5))
	print("Decimal", 6, "= Binary",hex(6))
	print("Decimal", 7, "= Binary",hex(7))
	print("Decimal", 8, "= Binary",hex(8))
	print("Decimal", 9, "= Binary",hex(9))
	print("Decimal", 10, "= Binary",hex(10))
else:
	print("Invalid, try again")
